#+TITLE:
#+AUTHOR: 
#+EMAIL: 
#+KEYWORDS:
#+DESCRIPTION:
#+TAGS:
#+LANGUAGE: en
#+OPTIONS: toc:nil
#+PANDOC_OPTIONS:
#+STARTUP: hidestars showall

* remarks

- not found in 1993/07/18/0622176: "Nintendo, the king of video games"

* some statistics

** number of articles
#+BEGIN_SRC sh :dir /hadoopext:vossanto
  for i in $(seq 1987 2007); do
    echo -ne "$i\t"
    tar tzvf nyt_corpus_$i.tar.gz | grep "xml$" | wc -l
  done
#+END_SRC

|  year | articles |
|-------+----------|
|  1987 |   106104 |
|  1988 |   104541 |
|  1989 |   102818 |
|  1990 |    98812 |
|  1991 |    85135 |
|  1992 |    82685 |
|  1993 |    79200 |
|  1994 |    74925 |
|  1995 |    85392 |
|  1996 |    79077 |
|  1997 |    85396 |
|  1998 |    89163 |
|  1999 |    91074 |
|  2000 |    94258 |
|  2001 |    96282 |
|  2002 |    97258 |
|  2003 |    94235 |
|  2004 |    91362 |
|  2005 |    90004 |
|  2006 |    87052 |
|  2007 |    39953 |
|-------+----------|
| *sum* |  1854726 |
#+TBLFM: @23$2=vsum(@I..@II)

** number of candidates
#+BEGIN_SRC sh :dir /hadoopext:vossanto
  echo -e "year\tv01\tv02\tv03"
  for i in $(seq 1987 2007); do
    v01=$(cat v01/vossanto_$i.tsv | wc -l)
    v02=$(cat v02/vossanto_$i.tsv | wc -l)
    v03=$(cat v03/vossanto_$i.tsv | wc -l)
    echo -ne "$i\t$v01\t$v02\t$v03\n"
  done
#+END_SRC

** number of vossantos

#+begin_src emacs-lisp :results none
(setq org-babel-python-command "python3")
#+end_src

#+BEGIN_SRC python :results output table raw
  year = None
  count = None
  with open("README.md", "r") as f:
      for line in f:
          # find "## Examples"
          if line.startswith("## Examples"):
              year = 0
              continue
          # find "### YEAR"
          if year is not None and line.startswith("### "):
              # output count for previous year
              if year > 0:
                  print(year, count, sep='\t')
              year = int(line[4:8])
              count = 0
              continue
          # find Vossantos
          if year is not None and year > 0 and line.startswith("- "):
              count += 1
              continue
      print(year, count, sep='\t')
#+END_SRC

#+RESULTS:
1987	19
1988	17
1989	20
1990	24
1991	20
1992	24
1993	28
1994	28
1995	26
1996	24
1997	35
1998	38
1999	35
2000	36
2001	30
2002	38
2003	39
2004	38
2005	35
2006	30
2007	13

** final result

# plot with: M-x org-plot/gnuplot
#+PLOT: title:"Vossanto" ind:1 deps:(4) type:2d with:linespoints set:grid
|  year | articles |   v01 |   v01% | VOSS01 | VOSS01‰ | prec01 |   v02 |   v02% |  v03 |   |
|-------+----------+-------+--------+--------+---------+--------+-------+--------+------+---|
|  1987 |   106104 |   792 |   7.46 |     19 |    0.18 |   2.41 |  1030 |   9.71 | 1127 |   |
|  1988 |   104541 |   734 |   7.02 |     17 |    0.16 |   2.28 |   963 |   9.21 | 1051 |   |
|  1989 |   102818 |   775 |   7.54 |     20 |    0.19 |   2.52 |   989 |   9.62 | 1067 |   |
|  1990 |    98812 |   668 |   6.76 |     24 |    0.24 |   3.55 |   860 |   8.70 |  946 |   |
|  1991 |    85135 |   583 |   6.85 |     20 |    0.23 |   3.36 |   781 |   9.17 |  861 |   |
|  1992 |    82685 |   605 |   7.32 |     24 |    0.29 |   3.96 |   777 |   9.40 |  854 |   |
|  1993 |    79200 |   503 |   6.35 |     28 |    0.35 |   5.51 |   658 |   8.31 |  742 |   |
|  1994 |    74925 |   540 |   7.21 |     28 |    0.37 |   5.13 |   689 |   9.20 |  749 |   |
|  1995 |    85392 |   626 |   7.33 |     26 |    0.30 |   4.09 |   790 |   9.25 |  853 |   |
|  1996 |    79077 |   584 |   7.39 |     24 |    0.30 |   4.06 |   773 |   9.78 |  841 |   |
|  1997 |    85396 |   632 |   7.40 |     35 |    0.41 |   5.54 |   781 |   9.15 |  835 |   |
|  1998 |    89163 |   667 |   7.48 |     38 |    0.43 |   5.75 |   859 |   9.63 |  925 |   |
|  1999 |    91074 |   604 |   6.63 |     35 |    0.38 |   5.73 |   822 |   9.03 |  881 |   |
|  2000 |    94258 |   420 |   4.46 |     36 |    0.38 |   8.52 |   604 |   6.41 |  654 |   |
|  2001 |    96282 |   365 |   3.79 |     30 |    0.31 |   8.18 |   525 |   5.45 |  585 |   |
|  2002 |    97258 |   340 |   3.50 |     38 |    0.39 |  11.14 |   497 |   5.11 |  574 |   |
|  2003 |    94235 |   331 |   3.51 |     39 |    0.41 |  11.68 |   535 |   5.68 |  609 |   |
|  2004 |    91362 |   294 |   3.22 |     38 |    0.42 |  13.04 |   487 |   5.33 |  533 |   |
|  2005 |    90004 |   300 |   3.33 |     35 |    0.39 |  11.71 |   466 |   5.18 |  517 |   |
|  2006 |    87052 |   260 |   2.99 |     30 |    0.34 |  11.37 |   405 |   4.65 |  457 |   |
|  2007 |    39953 |   121 |   3.03 |     13 |    0.33 |  10.89 |   187 |   4.68 |  211 |   |
|-------+----------+-------+--------+--------+---------+--------+-------+--------+------+---|
| *sum* |  1854726 | 10744 | 120.57 |    597 |    0.31 | 140.42 | 14478 | 162.65 |      |   |
| *avg* |    88320 |   512 |   5.74 |     28 |    0.32 |   6.69 |   689 |   7.75 |      |   |
#+TBLFM: $4=($-1/$2)*1000;%0.2f::$6=($-1/$-4)*1000;%0.2f::$7=($-1/$-3)*100;%0.2f::$9=($-1/$2)*1000;%0.2f::@23$2=vsum(@I..@II)::@23$3=vsum(@I..@II)::@23$4=vsum(@I..@II)::@23$5=vsum(@I..@II)::@23$7=vsum(@I..@II)::@23$8=vsum(@I..@II)::@23$9=vsum(@I..@II)::@24$2=@-1/vlen(@I..@II);%0.0f::@24$3=@-1/vlen(@I..@II);%0.0f::@24$4=@-1/vlen(@I..@II);%0.2f::@24$5=@-1/vlen(@I..@II);%0.0f::@24$7=@-1/vlen(@I..@II);%0.2f::@24$8=@-1/vlen(@I..@II);%0.0f::@24$9=@-1/vlen(@I..@II);%0.2f


* special/dubious cases
** the PLACE version of 

#+BEGIN_SRC sh :results raw output
  grep -i version README.md
#+END_SRC

- *Sassy*, the *United States version* of *Dolly* (1987/08/24/0068801)
- *Marks & Spencer* is the *British version* of *Wal-Mart* (1992/11/09/0569053)
- *MediCal*, the *California version* of *Medicaid* (1994/07/11/0698715)
- *Buran*, the *Russian version* of the *space shuttle* (1995/03/21/0750052)
- *Macco*, the *Calabrian version* of the *dish* (1997/02/14/0908831)
- *Voluntary Service Overseas*, the *British version* of the *Peace Corps* (1997/12/21/0981913)
- *Take That*, the *British version* of the *Backstreet Boys* (1999/05/10/1106572)
- *Much Music* is the *Canadian version* of *MTV* (2000/02/06/1174454)
- *Kakavia*, the *Greek version* of *bouillabaisse* (2000/04/19/1193000)
- *Fado* is the *Portuguese version* of the *blues* (2002/11/24/1443088)

** the PLACE equivalent of 

#+BEGIN_SRC sh :results raw output
  grep -i equivalent README.md
#+END_SRC

- *New South Wales*, the *Georgian equivalent* of *deep space* (1987/01/25/0007151)
- *Olivier Award*, the *English equivalent* of the *Tony Award* (1987/02/01/0009058)
- the *Wireless Service*, the *German equivalent* of the *BBC* (1987/04/05/0027535)
- the *Cesars* - the *French equivalent* of *Oscars* (1987/06/29/0052991)
- the *Olivier Award* - the *British equivalent* of a *Tony* (1987/07/10/0055426)
- *Laurence Olivier Award*, the *English equivalent* of the *Tony Award* (1987/12/22/0103798)
- *Olivier Award*, the *English equivalent* of the *Tony* (1988/02/01/0114868)
- *Nahlas* - the *Slovak equivalent* of *glasnost* (1988/03/03/0124041)
- the *Young Pioneers* - the *Soviet equivalent* of the *Boy Scouts* (1988/03/21/0129426)
- *Olivier Award*, the *British equivalent* of the *Tony* (1990/09/06/0382052)
- the *Grey Cup*, the *Canadian equivalent* of the *Super Bowl* (1990/11/25/0403957)
- *Superintendent Martin Beck*, the *Scandinavian equivalent* of *Sherlock Holmes* (1993/02/21/0591703)
- *Monoprix*, the *French equivalent* of *Kmart* (1993/04/27/0605068)
- *Ariels*, the *Mexican equivalent* of *Oscars* (1994/03/20/0675424)
- the *Performer*, the *British equivalent* of *Variety* (1994/04/24/0682538)
- *Gosatomnadzor or GAN*, the *Russian equivalent* of the *Nuclear Regulatory Commission* (1994/08/19/0707174)
- *Fairfax*, the *Los Angeles equivalent* of the *Lower East Side* (1995/05/11/0761719)
- *Hulton Deutsch*, the *European equivalent* of the *Bettman Archive* (1997/05/18/0930910)
- the *Inland Revenue*, the *British equivalent* of the *Internal Revenue Service* (1997/09/06/0955411)
- *Business Review Weekly*, the *Australian equivalent* of *Business Week* (1997/09/13/0957036)
- *Muchmusic*, the *Canadian equivalent* of *MTV* (1997/09/28/0960868)
- the *Tax Administration Service*, the *Mexican equivalent* of the *Internal Revenue Service* (1997/11/10/0972063)
- *Eurosport*, the *European equivalent* of *ESPN* (1998/02/23/0997564)
- *Special Unit Corps*, the *Yugoslav equivalent* of the *American Special Forces* (1999/04/01/1096836)
- *Central Service of Information*, the *Greek equivalent* of the *Central Intelligence Agency* (1999/06/28/1119302)
- *Juno Awards*, the *Canadian equivalent* of the *Grammys* (1999/10/17/1146042)
- *Olivier Awards*, the *London equivalent* of the *Tony Awards* (2000/07/05/1212567)
- the *Whitbury New Town Leisure Center*, the *English equivalent* of a *health club* (2000/10/20/1240169)
- *Olivier Award*, the *London equivalent* of the *Tony* (2003/03/02/1468848)
- *Yomiuri Giants*, the *Japanese equivalent* of the *Yankees* (2004/03/28/1569955)
- *Oden* is the *Japanese equivalent* of *chicken soup* (2004/03/10/1565172)
- *Mabahith*, the *Egyptian equivalent* of the *F.B.I.* (2005/04/08/1663228)
- *Rijkswaterstaat*, the *Dutch equivalent* of the *Corps of Engineers* (2005/11/29/1721150)
- *Bafta*, the *British equivalent* of the *Academy Awards* (2006/03/06/1744762)
- *Biz Cool*, the *Japanese equivalent* of *business casual* (2006/06/24/1771315)
- *Liberty*, the *British equivalent* of the *American Civil Liberties Union* (2006/06/25/1771465)
- *Chalkhill Estates in London*, the *British equivalent* of a *housing project* (2006/11/01/1801327)

** the pioneer, king, queen, ... of 

#+BEGIN_SRC sh :results raw output
  for term in apostle Boys Capital counterpart Czar Darling dean Diva Duke Emperor Father Giant [gG]od [kK]ing Land Lord Marquis [mM]aster [mM]ecca [pP]ioneer Princess Queen Satan Sultan Valley Voice; do
      echo "- $term ::"
      grep $term README.md | sed "s/^/  /"
  done
#+END_SRC

- apostle ::
  - *Milton Friedman*, the *American apostle* of *free-market economics* (1989/07/12/0265229)
- Boys ::
  - the *Islanders*, the *Boys* of *Winter* (1992/01/24/0502719)
  - *Take That*, the *British version* of the *Backstreet Boys* (1999/05/10/1106572)
- Capital ::
  - the *Dandelion Capital* of the *World* (also known as *Vineland, N.J.*) and the *Fire Hydrant Capital* of the *World* (*Albertville, Ala.*, of course) (2001/07/12/1308610)
  - *Crawford*, the *Deer Capital* of *Nebraska*, or *Llano*, the *Deer Capital* of *Texas* (2001/07/12/1308610)
  - *Ogallala*, the *Cowboy Capital* of *Nebraska* (2001/11/10/1341592)
- counterpart ::
  - *Europcar*, the *European counterpart* of *National Car Rental* (1989/03/05/0228921)
- Czar ::
  - *Albert*, the *Czar* of *Sportscast Shtick* (1992/11/06/0568322)
  - *Christopher (Mad Dog) Russo*, the *Czar* of *Mystification* (1993/11/30/0653147)
- Darling ::
  - *Dainty June*, the *Darling* of *Vaudeville* (1998/08/16/1039368)
- dean ::
  - *Roy Lancaster*, the *English dean* of *plant explorers* (1999/06/20/1116753)
- Diva ::
  - If *Kelly Hoppen* is the *Design Diva* of *London*, then *Rita Konig* is the *Design It Girl*. (2002/12/26/1451541)
- Duke ::
  - *Dukes Stadium* is the *Coors Field* of the *minor leagues* (1996/07/08/0863204)
  - When the bassist *Harry Goodman* began his own swing band in the 1940's, posters billed him as the brother of *Benny Goodman*, the *King* of *Swing*. (Perhaps he could have been the *Duke* of *Swing*, if it weren't for Ellington.) (1999/06/06/1113206)
- Emperor ::
  - *Mr. John*, the *Emperor* of *Fashion* (1988/05/02/0141129)
- Father ::
  - *Norbert Wiener*, the *Father* of *Cybernetics* (2005/03/01/1653553)
- Giant ::
  - the *Giants*, the *New York Titans* of the *American Football League* (1987/01/28/0007820)
  - Forget the Yankees of Reggie, the Giants of Taylor, the Mets of Carter and Hernandez, even the Knicks of Reed and DeBusschere. The Islanders won like the old, old New York Yankees and they charmed like the old, old Brooklyn Dodgers (1992/03/04/0511581)
  - *Mont Ventoux*, the *Giant* of *Provence* (2002/07/22/1410302)
  - *Lance Armstrong*, the *Giant* of the *Tour* (2002/07/22/1410302)
  - *Yomiuri Giants*, the *Japanese equivalent* of the *Yankees* (2004/03/28/1569955)
  - *Styx Valley*, the *Valley* of the *Giants* (2004/09/12/1610579)
  - *Mont Ventoux*, the *Giant* of *Provence* (2005/06/05/1678016)
- [gG]od ::
  - Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, the *Bela Lugosi* of *American Politics*, Richard the Chicken-Hearted, the *Nero* of *Our Times*, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick. (1987/01/29/0008167)
  - If *Toys "R" Us* is the *Gulliver* of *toy sellers*, then *Nintendo* is the *Godzilla of toys*  (1990/12/06/0406527)
  - *Mount Meru*, the *Olympus* of the *Hindu gods* (1992/06/21/0537615)
  - *Mike Wallace*, the *Godzilla* of the *tube* (1992/10/26/0565903)
  - *Martin Margiela*, the *Belgian godfather* of *deconstructionism* (1994/09/11/0711455)
  - *Michael Jordan* is the *God* of *Chicago* (1995/03/12/0748227)
  - *James Brown*, the *Godfather* of *Soul* (1997/02/27/0911924)
  - *Momo*, the *God* of *Bad-mouthing* (1997/06/14/0936821)
  - *James Brown*, *Godfather* of *soul music* (1999/06/27/1119059)
  - *Yoshinori Watanabe*, the *Japanese godfather* of the *yakuza* (2000/04/02/1188831)
  - *James Brown*, the *Godfather* of *Soul* (2000/04/13/1191452)
  - *Strauss*, the *Jupiter* of the *composer gods* (2002/01/06/1357042)
  - *Dionysos*, the *God of drama* (2004/06/27/1592422)
  - *James Brown*, the *Godfather* of *Soul* (2006/03/25/1749390)
  - *James Brown*, the *Godfather* of *Soul* (2007/05/27/1850236)
- [kK]ing ::
  - Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, the *Bela Lugosi* of *American Politics*, Richard the Chicken-Hearted, the *Nero* of *Our Times*, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick. (1987/01/29/0008167)
  - *Dana Dane*, the *King* of *Rap*, (1987/11/26/0096606)
  - If the *American Budweiser* is the *King of Beers*, what does that make the *Czech Budweiser*? Why, none other than the *Beer* of *Kings*, if negotiations between the two brewers succeed. (1991/03/10/0429088)
  - *Ludwig*, the *Mad King* of *Bavaria* (1993/07/14/0621506)
  - *James Vacca*, the *King* of *Clean* (1994/08/21/0707596)
  - *Alan King*, the *Spike Lee* of *tennis* (1994/09/10/0711111)
  - *Hillary*, the *Queen* of *Cups*, is going to go to bat for *Bill*, the *King* of *Wands* (1994/12/25/0733168)
  - *Riley*, the *King* of *Heat* (1995/11/25/0811302)
  - *Viktor Dysenko*, the *Russian king* of *pulp* (1997/05/14/0929759)
  - *Zulu King Shaka*, the *Genghis Khan* of *Africa* (1998/02/05/0993081)
  - If *Nelson Mandela* is the *George Washington* of this *new democracy*, the kind of giant among men who turns down offers to be king, then *Mr. Mbeki* is *its* *John Adams*. (1999/06/04/1112428)
  - When the bassist *Harry Goodman* began his own swing band in the 1940's, posters billed him as the brother of *Benny Goodman*, the *King* of *Swing*. (Perhaps he could have been the *Duke* of *Swing*, if it weren't for Ellington.) (1999/06/06/1113206)
  - *Youngman* is the *King* of *One Liners* (2001/01/07/1260710)
  - *Bing Crosby*, the *Unsung King* of *Song* (2001/02/11/1269897)
  - *George Duboeuf*, called *King* of *Beaujolais* (2003/04/09/1479284)
  - the *late Jack Kirby*, the *King* of *Comics* (2003/08/27/1514969)
  - *Lil' John*, the *King* of *Crunk* (2004/05/23/1583885)
  - *Moon Mullican*, the *King* of the *Hillbilly Piano* (2006/06/04/1766403)
  - *Benny Goodman*, the *King* of *Swing* (2006/11/22/1806655)
- Land ::
  - *Ann Landers*, the *Oprah Winfrey* of *newspapers*, (1996/01/17/0823245)
  - *Jersey Shore*, the *Land* of *Imposition* (2002/07/28/1411586)
- Lord ::
  - *Amado Carrillo Fuentes*, the *Lord* of the *Skies* (1997/05/24/0932060)
  - *Frank Pembleton*, the *Lord* of the *Box* (1998/03/29/1005941)
  - *Lord's Cricket Ground*, the *Yankee Stadium* of the *sport* (2000/12/07/1253266)
- Marquis ::
  - *Pittsburgh's Mario Lemieux*, the *Marquis* of *Marquees* (1993/05/04/0606594)
- [mM]aster ::
  - the *Masters*, the "*cathedral* of *golf*"  (1999/04/11/1099455)
  - *Raymond Chandler*, the *Anglo master* of *crime fiction* (1999/07/13/1123045)
  - *Alan Greenspan* is the *Master* of the *Universe* (1999/12/19/1162227)
  - *Yasujiro Ozu*, the *Japanese master* of *emotional understatement* (2003/08/08/1510478)
  - *Terry Riley*, the *California Minimalist*; *Astor Piazzolla*, the *Argentine master* of the *nuevo tango*; and *John Zorn*, the *New York bender* of *genres* (2004/01/11/1549709)
  - *Jon Jerde*, the *California master* of *mall design* (2007/01/04/1816247)
  - *Fred Sandback*, the *American master* of *ethereal string geometries* (2007/06/15/1854531)
- [mM]ecca ::
  - *Seattle*, the *American mecca* of *waste reduction* (1991/12/12/0493523)
  - *University of California at Davis*, the *American mecca* of *viniculture education* (1998/08/15/1039075)
  - *America* is the *Mecca* of that *ideology* (2001/11/27/1346329)
  - *Las Vegas*, the *Mecca* of *boxing* (2003/11/30/1539102)
  - the *southern French city of Grasse*, the *Mecca* of *perfume manufacturers* (2004/11/05/1624748)
  - *New York* is the *Mecca* of *basketball* (2007/04/05/1838196)
- [pP]ioneer ::
  - the *Young Pioneers* - the *Soviet equivalent* of the *Boy Scouts* (1988/03/21/0129426)
  - *Samuel Barber*, the *Pioneer* of the *American Symphony* (1996/09/22/0878602)
  - *Russel Wright*, the *American pioneer* of *modern product design* (1999/06/05/1112688)
- Princess ::
  - *Gillian Anderson* is the *Pauper* of *professional experience*, *Brenda Blethyn* is the *Princess* (1991/02/20/0424794)
  - Call her the *Princess* of *Patina*, the *Queen* of *Faux* (2000/07/30/1218802)
- Queen ::
  - *Queen Victoria*, the *Great Satan* of the *time* (1988/02/03/0115425)
  - *Tiramisu*, the *New Queen* of *Italian Desserts* (1991/03/13/0429693)
  -  *Luis Cisneros*, better known to colleagues as *Sandra*, the *Queen* of the *Bois* (1992/01/11/0499353)
  - *Hillary*, the *Queen* of *Cups*, is going to go to bat for *Bill*, the *King* of *Wands* (1994/12/25/0733168)
  - *Aretha Franklin*, the *Queen* of *Soul* (1996/05/02/0847754)
  - "Some people say *Claire Shulman* is the *Golda Meir* of *Queens*. [...] I say *Golda Meir* was the *Claire Shulman* of *Israel*." (1996/05/21/0852275)
  - the *former Kiva Shliuger*, performs regularly as a fire-eater known as Combustible Kiva, the *Queen* of *Kerosene* (1998/06/07/1022995)
  - *Queens*, the *Rodney Dangerfield* of *boroughs* (1999/05/15/1107670)
  - Call her the *Princess* of *Patina*, the *Queen* of *Faux* (2000/07/30/1218802)
  - *Harris* has been called the *Queen* of *Country Music*, the *Angel* of *This*, the *Sweetheart* of *That* (2000/09/03/1227433)
  - *Celia Cruz*, the *Queen* of *Salsa* (2001/03/16/1278191)
  - *Leona Helmsley*, the *Queen* of *Mean* (2002/02/27/1371153)
  - *Hillary*, the *Cattle Queen* of *commodities trading* (2002/07/10/1407094)
  - *Alice Gordon of Massapequa Park* is the *Queen Mother* of the *Long Island Lusties* (2003/03/30/1476594)
  - *Ouidad*, the *Queen* of *Curl* (2004/02/15/1559089)
- Satan ::
  - *Queen Victoria*, the *Great Satan* of the *time* (1988/02/03/0115425)
  - the *Walt Disney Company* is the *Great Satan* of *this jeremiad* (1997/04/06/0920680)
- Sultan ::
  - *Babe Ruth*, the *Sultan* of *Swat* (1995/11/27/0811882)
  - *Kenneth Starr*, the *Sultan* of the *Subpoena* (1998/03/20/1003494)
- Valley ::
  - *Bangalore*, India, the *Silicon Valley* of *South Asia* (1997/06/19/0938068)
  - *Dick French Jr*. is the *Ted Turner* of the *Hudson Valley* (1998/04/26/1012685)
  - *Hsinchu Science Park*, *Silicon Valley* of *Taiwan* (1999/09/22/1139658)
  - *Las Cruces*, the *Mesilla Valley* of *southern New Mexico* (2003/03/09/1470804)
  - *Styx Valley*, the *Valley* of the *Giants* (2004/09/12/1610579)
  - the *only alternative* to the *Canyon* of *Heroes* is the *Valley* of *Doom* (2004/09/30/1615408)
  - *Ravenswood* is the *Death Valley* of *New York City* (2005/07/23/1689358)
  - *Garberville*, the *Central Valley* of *marijuana* (2006/08/28/1786070)
- Voice ::
  - *Celebi*, the *Voice* of the *Forest* (2002/10/11/1431006)
  - *Darren Romeo*, the *Voice* of *Magic* (2004/09/19/1612812)

** If ...

#+BEGIN_SRC sh :results raw output
  grep -E "^- \"?If" README.md 
#+END_SRC

- If *Mr. Moynihan* is the *Sherlock Holmes* of the *fiscal story*, then *Mr. Stockman* is at once *its Dr. Watson* and *its Moriarty*. (1988/04/17/0136766)
- If *Wrigley* is the *Faneuil Hall Marketplace* of *ball parks*, *Comiskey* is *Paddy's Market*. (1990/09/30/0387487)
- If *Toys "R" Us* is the *Gulliver* of *toy sellers*, then *Nintendo* is the *Godzilla of toys*  (1990/12/06/0406527)
- If the *American Budweiser* is the *King of Beers*, what does that make the *Czech Budweiser*? Why, none other than the *Beer* of *Kings*, if negotiations between the two brewers succeed. (1991/03/10/0429088)
- If *Woo* is the *Bill Clinton* of the *race*, then *Riordan* is the *Ross Perot* (1993/04/18/0602876)
- If *Klensch* is the *Cronkite* of the *rag trade*, *Crawford* is a *game, albeit hipper, Kathie Lee* (1993/10/24/0644390)
- If *Vanilla Ice* is the *Pat Boone* of *hip-hop*, watering down a vibrant black musical form to make it appeal to a generic pop audience, then *G. Love* is *its* *Elvis Presley*. (1994/06/20/0694707)
- If *Kentucky* is the *Roman Empire* of *college basketball*, the *Nets' franchise* is the *Roamin' Empire* of *pro basketball*. (1996/05/31/0854362)
- If *Wynton Marsalis* is the *Steven Spielberg* of the *jazz scene*, the alto saxophonist *Steve Coleman* has a strong claim to being *its* *Stanley Kubrick*. (1999/05/02/1104452)
- If *Nelson Mandela* is the *George Washington* of this *new democracy*, the kind of giant among men who turns down offers to be king, then *Mr. Mbeki* is *its* *John Adams*. (1999/06/04/1112428)
- If *Houston's cozy new Enron Field* is the *Rhode Island* of *ballparks*, then *Comerica Park* is *Alaska* (2000/05/14/1199574)
- If *Kelly Hoppen* is the *Design Diva* of *London*, then *Rita Konig* is the *Design It Girl*. (2002/12/26/1451541)
- If *Mariano Rivera of the Yankees* is the *Mr. October* of *closers*, *Gagne* is the *Mr. Season*. (2004/05/18/1582589)
- "If *bin Laden* is the *Robin Hood* of *jihad*," the authors write, then *Abu Musab al-Zarqawi* "has been its *Horatio Alger*, and *Iraq* his *field of dreams*." (2005/11/20/1719129)
- If the *vast, empty plain of eastern Montana* is the *Saudi Arabia* of *coal*, then *Gov. Brian Schweitzer* may be its *Lawrence*. (2005/11/21/1719391)
- If *Buenos Aires* is the *Paris* of *South America*, *Quebec City* is the *Paris* of *North America*. (2006/02/19/1740811)

** more than three parts (but not "If ...")

#+BEGIN_SRC sh :results raw output
  grep -E "(\*.*){7,}" README.md | grep -v -E "^- \"?If" 
#+END_SRC

- Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, the *Bela Lugosi* of *American Politics*, Richard the Chicken-Hearted, the *Nero* of *Our Times*, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick. (1987/01/29/0008167)
- *Sax* dressed alongside *Kirk Gibson* and *Mickey Hatcher*, the *Three Musketeers* of *Hyperactivity* (1988/11/27/0201849)
- *Guzman* is regarded as "the *Stalin* of *Patchogue*, the *Idi Amin* of *Long Island*" (1988/12/06/0204254)
- *Barnum* - the *Michelangelo* of *buncombe*, *hokum*, *hoopla* and *ballyhoo* (1989/06/06/0256423)
- the *New Orleans chef Paul Prudhomme*, the *Louis Armstrong* of *jambalaya*, *crawfish pie* and *file gumbo*  (1989/08/17/0276060)
- *Waterman*, the *Rolls-Royce* of *pens* acquired in 1987, and *Papermate*, the *Chevrolet* of *pens* (1990/02/25/0329728)
- "*New York State* is the *Cadillac* of *social services*," Mr. Alfonso said. "*Other states* have *Volkswagens*."  (1990/11/26/0404144)
- "*New York* is the *Cadillac* of *welfare states*," he said. "We can't afford it anymore. What we need is *Chevys* and *Fords* in this state." (1991/01/31/0419226)
- *Gillian Anderson* is the *Pauper* of *professional experience*, *Brenda Blethyn* is the *Princess* (1991/02/20/0424794)
- A *bagel's* the *Shakespeare*, the *Tolstoy* of *flour* (1991/03/27/0433213)
- *Lady Caroline Wrey*, otherwise known as *Lady Velcro*, the *Barbara Woodhouse* of *windows* (1991/10/24/0482422)
-  *Luis Cisneros*, better known to colleagues as *Sandra*, the *Queen* of the *Bois* (1992/01/11/0499353)
- But if *Jordan* is the *Chuck Yeager* of *basketball*, *Julius Erving* was its *Charles Lindbergh* and *Connie Hawkins* was its *Wright Brothers*. (1992/05/07/0526474)
- *Romario* is the *Michael Jordan* of *soccer* and *Bebeto* is the *Magic Johnson* of *soccer* (1994/07/05/0697643)
- *Hillary*, the *Queen* of *Cups*, is going to go to bat for *Bill*, the *King* of *Wands* (1994/12/25/0733168)
- "Some people say *Claire Shulman* is the *Golda Meir* of *Queens*. [...] I say *Golda Meir* was the *Claire Shulman* of *Israel*." (1996/05/21/0852275)
- *Rutherford* is the *St. Julien* of the *valley*, and *Stag's Leap* is the *Pauillac* (1997/08/27/0953268)
- *Sushiko* is the *DMZ* of *Hollywood*, the *38th parallel* (1998/11/15/1062145)
- When the bassist *Harry Goodman* began his own swing band in the 1940's, posters billed him as the brother of *Benny Goodman*, the *King* of *Swing*. (Perhaps he could have been the *Duke* of *Swing*, if it weren't for Ellington.) (1999/06/06/1113206)
- Call her the *Princess* of *Patina*, the *Queen* of *Faux* (2000/07/30/1218802)
- *Cynthia Cooper* is the *Michael Jordan*, the *Larry Bird*, the *Magic Johnson* of *this league* (2000/08/28/1226010)
- *Harris* has been called the *Queen* of *Country Music*, the *Angel* of *This*, the *Sweetheart* of *That* (2000/09/03/1227433)
- the *Dandelion Capital* of the *World* (also known as *Vineland, N.J.*) and the *Fire Hydrant Capital* of the *World* (*Albertville, Ala.*, of course) (2001/07/12/1308610)
- *Crawford*, the *Deer Capital* of *Nebraska*, or *Llano*, the *Deer Capital* of *Texas* (2001/07/12/1308610)
- *Pepe Sanseli* is considered nothing less than the *Signore* of the *Sideburn*, the *Maestro* of the *Mustache*, *Herr Hair* (2001/11/25/1345804)
- *Terry Riley*, the *California Minimalist*; *Astor Piazzolla*, the *Argentine master* of the *nuevo tango*; and *John Zorn*, the *New York bender* of *genres* (2004/01/11/1549709)
- *Reggaeton*, the *Puerto Rican amalgam* of *dancehall reggae*, *gangsta rap* and *touches of salsa* (2004/09/03/1608662)
- the *only alternative* to the *Canyon* of *Heroes* is the *Valley* of *Doom* (2004/09/30/1615408)
- *Mesa Verde National Park* has been called the *Disneyland* of *ancient sites*, but it's also the *Anasazi* *Yosemite* (2004/10/15/1619273)

** Frequent

#+BEGIN_SRC sh
    grep "^-" README.md | sed -e "s/[^\*]*\*[^\*]*\*[^\*]*\*//" -e "s/\*.*//" | sort | uniq -c | sort -nr \
      | sed -e "s/^ *//" -e "s/ /\t/" | awk -F'\t' '{if ($1 >= 2) print $1"\t"$2}'
#+END_SRC

#+RESULTS:
| 9 | King                |
| 7 | Queen               |
| 7 | British equivalent  |
| 6 | Pied Piper          |
| 6 | Oscars              |
| 6 | Michael Jordan      |
| 5 | Michelangelo        |
| 5 | Holy Grail          |
| 5 | Godfather           |
| 5 | General Motors      |
| 5 | Cadillac            |
| 4 | Mecca               |
| 4 | English equivalent  |
| 4 | Babe Ruth           |
| 3 | Zelig               |
| 3 | Rodney Dangerfield  |
| 3 | Neil Young          |
| 3 | Microsoft           |
| 3 | Japanese equivalent |
| 3 | Giant               |
| 3 | Elvis               |
| 3 | Don Quixote         |
| 3 | Champs-Elysees      |
| 3 | Canadian equivalent |
| 3 | British version     |
| 2 | Yankee Stadium      |
| 2 | Wizard              |
| 2 | Wild West           |
| 2 | Voice               |
| 2 | Thomas Jefferson    |
| 2 | Super Bowl          |
| 2 | Sultan              |
| 2 | Stradivarius        |
| 2 | Simon Cowell        |
| 2 | Silicon Valley      |
| 2 | Rush Limbaugh       |
| 2 | Ronald Reagan       |
| 2 | Rolls-Royce         |
| 2 | Robert Moses        |
| 2 | Riviera             |
| 2 | Rangers             |
| 2 | Ralph Nader         |
| 2 | Picasso             |
| 2 | Paul Newman         |
| 2 | Paul Bunyan         |
| 2 | Nolan Ryan          |
| 2 | Mr. October         |
| 2 | Mozart              |
| 2 | Mister Rogers       |
| 2 | Mexican equivalent  |
| 2 | Mercedes-Benz       |
| 2 | Man                 |
| 2 | Mad Hatter          |
| 2 | Lord                |
| 2 | London equivalent   |
| 2 | Larry Bird          |
| 2 | John Wayne          |
| 2 | Johnny Appleseed    |
| 2 | James Brown         |
| 2 | Houdini             |
| 2 | Great Satan         |
| 2 | God                 |
| 2 | French equivalent   |
| 2 | Everest             |
| 2 | European equivalent |
| 2 | Energizer Bunny     |
| 2 | Ellis Island        |
| 2 | Detroit             |
| 2 | Czar                |
| 2 | Buddha              |
| 2 | Boswell             |
| 2 | Bill Gates          |
| 2 | Beverly Hills       |
| 2 | American mecca      |
| 2 | Age                 |

#+BEGIN_SRC sh :results raw output
  grep -E "Pied Piper" README.md
#+END_SRC

- *Gregory Hines* is the *Pied Piper* of *modern tap* (1992/12/25/0578860)
- *Robert B. Reich*, the *Pied Piper* of *high performance* (1994/06/05/0691688)
- *Russell Cera*, the *Pied Piper* of *education* (1994/07/03/0697153)
- *Carl Rogers*, the *Pied Piper* of "*self-actualization*" (1997/12/18/0981253)
- *Ken Kesey*, the *Pied Piper* of the *psychedelic era* (2001/11/11/1342116)
- *George Gilder*, the *Pied Piper* of *telecommunications investors* (2003/12/14/1543026)

#+BEGIN_SRC sh :results raw output
  grep -E "Michael Jordan" README.md
#+END_SRC

- *Romario* is the *Michael Jordan* of *soccer* and *Bebeto* is the *Magic Johnson* of *soccer* (1994/07/05/0697643)
- *Michael Jordan* is the *God* of *Chicago* (1995/03/12/0748227)
- *Bonfire*, the *Michael Jordan* of *dressage horses* (1998/11/05/1059693)
- *Brian Foster*, the *Michael Jordan* of *BMX racing* (1998/12/27/1072824)
- The stunt biker *Dave Mirra*, the *Michael Jordan* of the *dirt set* (2000/08/13/1222322)
- *Cynthia Cooper* is the *Michael Jordan*, the *Larry Bird*, the *Magic Johnson* of *this league* (2000/08/28/1226010)
- *McNabb* has been called the *Michael Jordan* of the *National Football League* (2001/01/08/1261308)

#+BEGIN_SRC sh :results raw output
  grep -E "Michelangelo" README.md
#+END_SRC

- *Barnum* - the *Michelangelo* of *buncombe*, *hokum*, *hoopla* and *ballyhoo* (1989/06/06/0256423)
- *Michael J. Deaver*, the *Michelangelo* of the *balloon drop* (1996/08/13/0871265)
- *Mel Gibson* is the *Michelangelo* of *this generation* (2003/08/02/1508990)
- *Kyle Avila*, the *Michelangelo* of the *bunch* (2006/12/17/1812547)
- *Mr. Gunn* is the *Michelangelo* of *the form* (2007/04/12/1839640)

#+BEGIN_SRC sh :results raw output
  grep -E "General Motors" README.md
#+END_SRC

- *Delta Pride*, the *General Motors* of *catfish processing factories* (1990/12/10/0407519)
- *Vaz Auto Works*, the *General Motors* of *Russia* (1992/03/08/0512599)
- *Starbucks Coffee*, the *General Motors* of *espresso* (1993/12/22/0657572)
- *Mr. Lovano* is the *General Motors* of *jazz* (1995/01/15/0736903)
- the *Estee Lauder Companies*, the *General Motors* of the *cosmetics world* (1999/01/10/1075990)

#+BEGIN_SRC sh :results raw output
  grep -E "Cadillac" README.md
#+END_SRC

- "*New York State* is the *Cadillac* of *social services*," Mr. Alfonso said. "*Other states* have *Volkswagens*."  (1990/11/26/0404144)
- "*New York* is the *Cadillac* of *welfare states*," he said. "We can't afford it anymore. What we need is *Chevys* and *Fords* in this state." (1991/01/31/0419226)
- *Eldredge* is the *Cadillac* among *Ferraris* (2002/02/12/1367217)
- the *Eldorado* has been the *Cadillac* of *Cadillacs* (2002/05/10/1390973)
- *MagLiner*, the *Cadillac* of *hand trucks* (2002/06/09/1399279)

#+BEGIN_SRC sh :results raw output
  grep -E "Babe Ruth" README.md
#+END_SRC

- *Eddie Shore*, the *Babe Ruth* of *hockey* (1988/11/04/0194523)
- *Jack B. Solerwitz* is the *Babe Ruth* of *ripoffs* (1993/03/19/0596753)
- *Rush Limbaugh*, the *Babe Ruth* of the *talk-show circuit* (1995/01/05/0735173)
- *Babe Ruth*, the *Sultan* of *Swat* (1995/11/27/0811882)
- *Eric Bergoust*, the *Babe Ruth* of *freestyle aerials* (2003/01/23/1458686)

