#+TITLE:
#+AUTHOR: 
#+EMAIL: 
#+KEYWORDS:
#+DESCRIPTION:
#+TAGS:
#+LANGUAGE: en
#+OPTIONS: toc:nil ':t H:5
#+STARTUP: hidestars overview
#+LaTeX_CLASS: scrartcl
#+LaTeX_CLASS_OPTIONS: [a4paper,11pt]
#+PANDOC_OPTIONS:

* "the ... of" Vossantos 

** preliminary note
With our initial exploratory approach we were able to cover a wide
variety of Vossantos but clearly missed some, as an analysis of some
[[file:~/projects/vossanto/examples/br.org#examples][examples]] shows. Therefore, we started to think about simplified
patterns which just match the source, for instance:

#+BEGIN_SRC 
  (a|the) (next|new|future|would-be)? ([A-Z][a-z]+ ){1,3} of
#+END_SRC

This pattern would not match the following examples from the NYT
corpus:
- "the Mick Jagger or Michael Jordan of"
- "the Michael Jordan and Magic Johnson of"
- "She could be the Michael Jordan that women's basketball hasn't yet had"
- "He has not been the Michael Jordan in the debates"
- "he was the Babe Ruth, the Michael Jordan, the Wayne Gretzky of racing"
- "if Mel Gibson really were Michelangelo of his generation"
- names which contain lower-case terms (e.g., "van Gogh")
- adjectives that further describe the target, e.g., "the abused
  pint-size Michelangelo of"

This again shows the difficulty to find a good balance between recall
and precision. We limited ourselves to the most basic pattern "the
... of", where "..."  represents one, two, or three Capitalised words.

** finding source candidates in the corpus
We search for sentences which contain the pattern
~\\bthe\\s([A-Z][a-z]+\\s+){1,3}of\\b~:
#+BEGIN_SRC sh
  for year in $(seq 1987 2007); do
    # searches for \bthe\s([A-Z][a-z]+\s+){1,3}of\b
    ./theof.py nyt_corpus_${year}.tar.gz > theof_${year}.tsv
  done
#+END_SRC

** most frequent candidates
In the NYT corpus we find 56583 hits for 1987 alone, which comprise
7702 distinct phrases, the ten most frequent ones are the following:
#+BEGIN_SRC sh
  awk -F'\t' '{print $2}' theof_1987.tsv| sort | uniq -c | sort -nr | head
#+END_SRC

| freq | phrase                |
|------+-----------------------|
| 6798 | the University of     |
| 1930 | the Department of     |
| 1495 | the Board of          |
|  845 | the Museum of         |
|  821 | the House of          |
|  770 | the Bank of           |
|  755 | the Federal Bureau of |
|  734 | the Office of         |
|  674 | the Government of     |
|  661 | the Secretary of      |

This clearly shows that the approach needs to be improved. Our idea is
to match the source candidates against a list of person names from
Wikidata.

** identifying source candidates in Wikidata
*** item has "instance of" property "human"

SPARQL query to retrieve all instances of "human":
#+BEGIN_SRC sparql
  SELECT ?item ?itemLabel WHERE
  {
    ?item wdt:P31 wd:Q5 .                  # instance of human
    SERVICE wikibase:label {               # ... include the labels
      bd:serviceParam wikibase:language "en"
    }
  }
#+END_SRC

Dowloading the data:
#+BEGIN_SRC sh :results silent
  curl \
      --header "Accept: text/tab-separated-values" \
      --output wikidata_humans.tsv \
      --globoff \
"https://query.wikidata.org/sparql?query=SELECT%20%3Fitem%20%3FitemLabel%20WHERE%0A%20%20{%0A%20%20%20%20%3Fitem%20wdt%3AP31%20wd%3AQ5%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20instance%20of%20human%0A%20%20%20%20SERVICE%20wikibase%3Alabel%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20...%20include%20the%20labels%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%0A%20%20%20%20}%0A%20%20}"
#+END_SRC

Checking the result:
#+BEGIN_SRC sh
  wc -l wikidata_humans.tsv
#+END_SRC

: 139649 wikidata_humans.tsv
Clearly some are missing here!

Let us try to get them without a label:
#+BEGIN_SRC sh :results silent
  curl \
      --header "Accept: text/tab-separated-values" \
      --output wikidata_humans_wo_labels.tsv \
      --globoff \
"https://query.wikidata.org/sparql?query=SELECT%20%3Fitem%20%3FitemLabel%20WHERE%0A%20%20{%0A%20%20%20%20%3Fitem%20wdt%3AP31%20wd%3AQ5%20.%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23%20instance%20of%20human%0A%20%20}"
#+END_SRC

#+BEGIN_SRC sh
  wc -l wikidata_humans_wo_labels.tsv
#+END_SRC

: 3455229 wikidata_humans_wo_labels.tsv

This looks much better. Is there a way to get a label for all of them?

With the [[https://www.mediawiki.org/wiki/Wikidata_Toolkit][Wikidata Toolkit]] and some Java code:
#+BEGIN_SRC java
  public void processItemDocument(final ItemDocument itemDocument) {
      // find an instance of "human"
      if (itemDocument.hasStatementValue("P31", Datamodel.makeWikidataItemIdValue("Q5"))) {
          final ItemIdValue itemId = itemDocument.getItemId();
          final MonolingualTextValue label = itemDocument.getLabels().get("en");
          if (label != null) {
              buf.write(csvEscape(itemId.getId()) + "\t" + csvEscape(label.getText()) + "\n");
          }
      }
  }
#+END_SRC
it is possible:
: Found 3454611 matching items after scanning 26132045 items.

Of those, 2801931 have a label:
#+BEGIN_SRC sh
  wc -l wikidata_humans.tsv
#+END_SRC

: 2801931 wikidata_humans.tsv
 We will use that file in the sequel.

*** "fictional character"
Retrieve all instances of any subclass of "fictional character":
#+BEGIN_SRC sparql
  SELECT (COUNT(DISTINCT ?item) AS ?count)
  WHERE
  {
    ?item wdt:P31 wd:Q5 .                  # instance of human
    SERVICE wikibase:label {               # ... include the labels
      bd:serviceParam wikibase:language "en"
    }
  }
#+END_SRC

#+BEGIN_SRC sh :results silent
  curl \
      --header "Accept: text/tab-separated-values" \
      --output wikidata_fictional_characters.tsv \
      --globoff \
"https://query.wikidata.org/sparql?query=SELECT%20%3Fitem%20%3FitemLabel%20WHERE%20{%0A%20%20%3Fitem%20%28wdt%3AP31%2Fwdt%3AP279*%29%20wd%3AQ95074.%0A%20%20SERVICE%20wikibase%3Alabel%20{%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20}%0A}%0AORDER%20BY%20DESC%28%3Fcount%29"
#+END_SRC

#+BEGIN_SRC sh
  wc -l wikidata_fictional_characters.tsv
#+END_SRC

: 46227 wikidata_fictional_characters.tsv
Seems reasonable.

** matching the phrases against the Wikidata candidates

We experiment first with the data from 1987 and match all sources in
the "the ... of" phrases against the Wikidata list of humans:
#+BEGIN_SRC sh 
  ./check_wikidata.py theof_1987.tsv wikidata_humans.tsv > theof_1987_wdfiltered.tsv
#+END_SRC

How many (distinct) phrases do remain?
#+BEGIN_SRC sh
  wc -l theof_1987_wdfiltered.tsv
  awk -F'\t' '{print $3}' theof_1987_wdfiltered.tsv | sort -u | wc -l
#+END_SRC

| 2520 | theof_1987_wdfiltered.tsv |
|  231 | distinct phrases          |

Which are the most frequent ones?
#+BEGIN_SRC sh
  awk -F'\t' '{print $3}' theof_1987_wdfiltered.tsv | sort | uniq -c | sort -nr | head
#+END_SRC

| freq | phrase            |
|------+-------------------|
|  821 | the House of      |
|  250 | the Church of     |
|  235 | the Hall of       |
|  140 | the Bill of       |
|   87 | the Freedom of    |
|   80 | the Governor of   |
|   60 | the Sultan of     |
|   60 | the Duke of       |
|   55 | the King of       |
|   40 | the Chancellor of |

So most of those are covered by rather unusual "names". We put them
into a blacklist:
#+BEGIN_SRC sh
  awk -F'\t' '{print $3}' theof_1987_wdfiltered.tsv | sort | uniq -c | sort -nr > blacklist.tsv
#+END_SRC
which we manually cleaned up.

Now we repeat the analysis:
#+BEGIN_SRC sh :results silent
  ./check_wikidata.py --blacklist blacklist.tsv theof_1987.tsv wikidata_humans.tsv > theof_1987_wdfiltered_blfiltered.tsv
#+END_SRC

How many results did we get?
#+BEGIN_SRC sh
  wc -l theof_1987_wdfiltered_blfiltered.tsv  
#+END_SRC

: 104 theof_1987_wdfiltered_blfiltered.tsv

Which were the most frequent ones?
#+BEGIN_SRC sh
  awk -F'\t' '{print $3}' theof_1987_wdfiltered_blfiltered.tsv | sort | uniq -c | sort -nr | head
#+END_SRC

| freq |                        |
|------+------------------------|
|    4 | the Horatio Alger of   |
|    4 | the Frank Sinatra of   |
|    3 | the Woody Allen of     |
|    3 | the Madonna of         |
|    2 | the Tom Seaver of      |
|    2 | the Pete Rose of       |
|    2 | the Joan Baez of       |
|    2 | the Jackie Robinson of |
|    2 | the Groucho Marx of    |
|    2 | the Abraham Lincoln of |

Much better! Let us repeat this process for all other years.

** handling the remaining years

First filtering step:
#+BEGIN_SRC sh :results silent
  export PYTHONIOENCODING=utf-8
  for year in $(seq 1987 2007); do
    ./check_wikidata.py theof_${year}.tsv wikidata_humans.tsv > theof_${year}_wd.tsv
  done
#+END_SRC
Now we have restricted the list to phrases which contain a source that
matches a Wikidata item with an "instance of" property of "human".

What's the distribution?
#+BEGIN_SRC sh
    echo "year all wd wd+bl"
    for year in $(seq 1987 2007); do
      echo $year \
           $(cat theof_${year}.tsv | wc -l) \
           $(cat theof_${year}_wd.tsv | wc -l) \
           $(cat theof_${year}_wd_bl.tsv | wc -l)
    done
#+END_SRC

| year |    all |    wd | wd+bl |
|------+--------+-------+-------|
| 1987 |  56513 |  2520 |   104 |
| 1988 |  55129 |  2640 |    88 |
| 1989 |  55602 |  2454 |   112 |
| 1990 |  53310 |  2608 |   117 |
| 1991 |  45822 |  2114 |   123 |
| 1992 |  41714 |  2232 |   120 |
| 1993 |  40338 |  2074 |   129 |
| 1994 |  37285 |  1867 |   131 |
| 1995 |  41839 |  2227 |   134 |
| 1996 |  40238 |  1972 |   154 |
| 1997 |  42737 |  2189 |   139 |
| 1998 |  46487 |  2654 |   189 |
| 1999 |  47431 |  2556 |   145 |
| 2000 |  44634 |  2165 |   187 |
| 2001 |  43209 |  2029 |   168 |
| 2002 |  44322 |  2236 |   183 |
| 2003 |  42874 |  2120 |   176 |
| 2004 |  41740 |  1943 |   146 |
| 2005 |  40774 |  2006 |   157 |
| 2006 |  40590 |  2071 |   182 |
| 2007 |  19004 |  1081 |   122 |
|------+--------+-------+-------|
|  sum | 921592 | 45758 |  3006 |
#+TBLFM: @23$2=vsum(@I..@II)::@23$3=vsum(@I..@II)::@23$4=vsum(@I..@II)

Filtering by blacklist:
#+BEGIN_SRC sh
  export PYTHONIOENCODING=utf-8
  for year in $(seq 1987 2007); do
    ./check_wikidata.py -b blacklist.tsv theof_${year}.tsv wikidata_humans.tsv > theof_${year}_wd_bl.tsv
  done
#+END_SRC

Extracting the blacklist:
#+BEGIN_SRC sh :results silent
    # current year
    YEAR=2007
    LAST_YEAR=$((YEAR-1))

    # previous year: create blacklist-cleaned file
    ./check_wikidata.py -b blacklist.tsv theof_${LAST_YEAR}.tsv wikidata_humans.tsv > theof_${LAST_YEAR}_wd_bl.tsv

    # last year: extend blacklist by all previous terms
    cp blacklist.tsv blacklist_lybl.tsv
    for iy in $(seq 1987 $LAST_YEAR); do
        awk -F'\t' '{print $3}' theof_${iy}_wd_bl.tsv | sort | uniq -c | sort -nr | \
            sed -e "s/^ *//" -e "s/ the /\t/" -e "s/ of$//" | awk -F'\t' '{print $2"\t"$1}' \
                                                                  >> blacklist_lybl.tsv
    done
    
    # now extract only new hits
    ./check_wikidata.py -b blacklist_lybl.tsv theof_${YEAR}.tsv wikidata_humans.tsv |\
        awk -F'\t' '{print $3}' | sort | uniq -c | sort -nr > bl.tsv
#+END_SRC

Now edit ~bl.tsv~ ... and then cleanup and append to existing file:
#+BEGIN_SRC sh :results raw
  sed -e "s/^ *//" -e "s/ the /\t/" -e "s/ of$//" bl.tsv | awk -F'\t' '{print $2"\t"$1}' >> blacklist.tsv
#  git commit blacklist.tsv

#+END_SRC

#+RESULTS:

... and repeat for the next year

** most frequent sources

#+BEGIN_SRC sh
  awk -F'\t' '{print $3}' theof_*_wd_bl.tsv \
      | sed -e "s/^the //" -e "s/ of$//" \
      | sort | uniq -c | sort -nr | head -n40
#+END_SRC

| count | source             |
|-------+--------------------|
|    74 | Michael Jordan     |
|    64 | Rodney Dangerfield |
|    47 | Madonna            |
|    37 | Babe Ruth          |
|    30 | Johnny Appleseed   |
|    26 | Mona Lisa          |
|    24 | Bill Gates         |
|    23 | Rembrandt          |
|    23 | Michelangelo       |
|    22 | Donald Trump       |
|    22 | Dalai Lama         |
|    21 | Tiger Woods        |
|    21 | Jackie Robinson    |
|    21 | Cary Grant         |
|    19 | John Wayne         |
|    18 | Napoleon           |
|    18 | Martha Stewart     |
|    16 | Mother Teresa      |
|    16 | Henry Ford         |
|    16 | Cal Ripken         |
|    15 | Ralph Nader        |
|    14 | Ross Perot         |
|    13 | Susan Lucci        |
|    12 | Walt Disney        |
|    12 | Rosa Parks         |
|    12 | Robin Hood         |
|    11 | Willie Horton      |
|    11 | Moses              |
|    10 | Virginia Court     |
|    10 | Oprah Winfrey      |
|    10 | King Kong          |
|    10 | Julia Child        |
|     9 | Tyson              |
|     9 | Muhammad Ali       |
|     9 | Mike Tyson         |
|     9 | James Dean         |
|     9 | Garbo              |
|     9 | Bill Clinton       |
|     8 | Woody Allen        |
|     8 | Magic Johnson      |

** format data for analysis

Put everything into a nice Markdown file:

#+BEGIN_SRC sh :results raw
  for year in $(seq 1987 2007); do
    echo "***" $year
    ./tsv2md.py theof_1987_wd_bl.tsv | head
    echo
  done
#+END_SRC

*** 1987
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1988
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1989
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1990
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1991
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1992
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1993
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1994
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1995
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1996
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1997
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1998
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 1999
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 2000
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 2001
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 2002
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 2003
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 2004
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 2005
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 2006
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''

*** 2007
- [Anthony Quinn](Q83484) (1987/01/02/0000232) ''I sometimes feel like *the Anthony Quinn of* my set.''
- [Madonna](Q1744) (1987/01/02/0000431)          True Blue                     LEAD: Jimmy Johnson is *the Madonna of* college football these days.
- [Madonna](Q1744) (1987/01/02/0000431) First it was Texas, then Southern Cal, now         Jimmy Johnson is *the Madonna of* college football these days.
- [Don Fernando](Q5292601) (1987/01/03/0000610) The other casting novelty was *the Don Fernando of* Richard J. Clark, his first at the Met.
- [Scott Joplin](Q191499) (1987/01/20/0005135) High points of the show included the obscure Cole Porter bonbons, ''Two Little Babes In the Wood'' and ''Nobody's Chasing Me,'' Eubie Blake and Noble Sissle's ''I'm Just Wild About Harry'' (performed both as a waltz and as a one-step to show how a simple time change can alter a song's character), and piano compositions by Ernesto Nazareth, ''*the Scott Joplin of* Brazil,'' that blended ragtime and tango.
- [Rich Little](Q1341644) (1987/01/21/0005602) A backup quarterback is *the Rich Little of* football, spending the week before a game doing an impression of the opposing team's quarterback.
- [Errol Flynn](Q93188) (1987/01/29/0008167) He is also known by less flattering terms, such as the Aging Right Wing Actor, the Not So Favor-ite Son and *the Errol Flynn of* the B's.
- [Bela Lugosi](Q34529) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Nero](Q1413) (1987/01/29/0008167) Mr. Reagan fares far better, nicknamewise, than some other Presidents in the compendium, including one known as Gloomy Gus, King Richard, *the Bela Lugosi of* American Politics, Richard the Chicken-Hearted, *the Nero of* Our Times, the Tarnished President, the Godfather, St. Richard the Commie Killer, President Truthful and Trickie Dick.
- [Abraham Lincoln](Q91) (1987/02/08/0011420) BORITT, GABOR S              LEAD: AT the Gettysburg cemetery, *the Abraham Lincoln of* Gore Vidal's novel barely gets through his first sentence - about the events in America ''four score and seven years ago'' - when the young Presidential secretary, John Hay, cynically observes that such rhetoric ''will please the radicals.''


